In [ ]:
import numpy as np
import cv2

cap1 = cv2.VideoCapture(r'./hw_1.mp4')   # play video file
cap2 = cv2.VideoCapture(r'./hw_2.mp4')   # play video file
 
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 15, (1280,720))
 
fgbg = cv2.bgsegm.createBackgroundSubtractorMOG(history=1, nmixtures=5, backgroundRatio=0.7)   # try history = 1


while True:
    ret, frame1 = cap1.read()
    ret, frame2 = cap2.read()
    
    if ret == True:
        # record cap location
        loc1 = cap1.get(cv2.CAP_PROP_POS_FRAMES) #525
        loc2 = cap2.get(cv2.CAP_PROP_POS_FRAMES) #261
        
        # print(frame1)
        # print(loc2)
#         if loc1 < 30:
#             b = cv2.resize(frame1,(1280,720),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#             out.write(b)
#         elif loc2 < 60:
#             a = cv2.resize(frame2,(1280,720),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#             out.write(a)
#         elif loc1 < 75 and loc2 < 75:
            
#             b = cv2.resize(frame1,(1280,720),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#             a = cv2.resize(frame2,(1280,720),fx=0,fy=0, interpolation = cv2.INTER_CUBIC)
#             out.write(a)
#             out.write(b)
            
        fgbg = cv2.bgsegm.createBackgroundSubtractorMOG(history=400, nmixtures=5, backgroundRatio=0.7)   # try history = 1
        frame1 = cv2.resize(frame1, (1280,720), interpolation = cv2.INTER_NEAREST)
    #     frame = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_LINEAR)

        fgmask = fgbg.apply(frame1)              # 到前景的遮罩圖
        # fgmask1 = fgbg1.apply(frame)            # 到前景的遮罩圖
        out.write(fgmask)
    else:
        break
    # cv2.imshow('frame',frame)
cap.release()
out.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

In [ ]:
cap2.get(cv2.CAP_PROP_FRAME_COUNT)

In [ ]:
import cv2
import math
import numpy as np
from PIL import Image
# import paddlehub as hub
from moviepy.editor import *

In [ ]:
import numpy as np
import cv2

def getFrame(video_name, save_path):
    """
    传入视频名称，将图像帧保存到save_path下
    """
    # 读取视频
    video = cv2.VideoCapture(video_name)

    # 获取视频帧率
    fps = video.get(cv2.CAP_PROP_FPS)
    # 获取画面大小
    width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
    size = (width, height)

    # 获取帧数
    frame_num = str(video.get(3))
    name = int(math.pow(10, len(frame_num)))
    ret, frame = video.read()
    while ret:
        cv2.imwrite(save_path + str(name) + '.jpg', frame)
        ret, frame = video.read()
        name += 1
    video.release()
    return fps, size

In [ ]:
getFrame(video, './')

In [ ]:
import cv2
import glob

path = r"./slow/*.jpg" 
result_name = 'output.mp4'

frame_list = sorted(glob.glob(path))
print("frame count: ",len(frame_list))

fps = 30
shape = cv2.imread(frame_list[0]).shape # delete dimension 3
size = (shape[1], shape[0])
print("frame size: ",size)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter(result_name, fourcc, fps, size)

for idx, path in enumerate(frame_list):
    frame = cv2.imread(path)
    # print("\rMaking videos: {}/{}".format(idx+1, len(frame_list)), end = "")
    current_frame = idx+1
    total_frame_count = len(frame_list)
    percentage = int(current_frame*30 / (total_frame_count+1))
    print("\rProcess: [{}{}] {:06d} / {:06d}".format("#"*percentage, "."*(30-1-percentage), current_frame, total_frame_count), end ='')
    out.write(frame)

out.release()
print("Finish making video !!!")

In [11]:
import numpy as np
import cv2
import dlib

cap = cv2.VideoCapture('./hw_2.mp4')

fgbg = cv2.createBackgroundSubtractorMOG2(history=1, detectShadows = True)   # MOG2
fgbg1 = cv2.createBackgroundSubtractorMOG2(history=200, detectShadows = False)   # MOG2
bs = cv2.createBackgroundSubtractorKNN(detectShadows=True)
detector = dlib.get_frontal_face_detector()  # Dlib 的人臉偵測器   

fourcc = cv2.VideoWriter_fourcc(*'MJPG') 
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))        # 取得畫面尺寸
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

out = cv2.VideoWriter('./homework2.avi', fourcc, fps, (800, 450))

video = []

while cap.isOpened():
    ret, frame = cap.read()
    if not ret : break
    # print(cap.get(cv2.CAP_PROP_POS_MSEC))
    lo = cap.get(cv2.CAP_PROP_POS_MSEC)
    # print(lo)
    # origin
    if lo < 1000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        cv2.putText(frame1, 'origin', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA)
        video.append(frame1)
        cv2.imshow('hhh', frame1)
        out.write(frame1)
    #MOG
    elif lo >= 1000 and lo < 3000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        fgmask = fgbg.apply(frame1)
        cv2.putText(fgmask, 'MOG', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        image = np.expand_dims(fgmask, axis=2)
        image = np.concatenate((image, image, image), axis=-1)
        video.append(image)
        cv2.imshow('hhh', image)
        out.write(image)
    # MOG
    elif lo >= 3000 and lo < 5000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        fgmask1 = fgbg1.apply(frame1)
        cv2.putText(fgmask1, 'MOG', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        image = np.expand_dims(fgmask1, axis=2)
        image = np.concatenate((image, image, image), axis=-1)
        video.append(image)
        cv2.imshow('hhh', image)
        out.write(image)
    # KNN
    elif lo >= 5000 and lo < 7000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        fg_mask = bs.apply(frame1)
        cv2.putText(fg_mask, 'KNN', (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
        image = np.expand_dims(fg_mask, axis=2)
        image = np.concatenate((image, image, image), axis=-1)
        video.append(image)
        cv2.imshow('hhh', image)
        out.write(image)
    # RGB
    elif lo >= 7000 and lo < 9000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2RGB)
        frame1 = cv2.flip(frame1, 1)
        cv2.putText(frame1, 'flip+RGB', (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA)
        video.append(frame1)
        cv2.imshow('hhh', frame1)
        out.write(frame1)
    elif lo >= 9000 and lo < 11000:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        cv2.putText(frame1, 'Gray', (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA)
        video.append(frame1)
        cv2.imshow('hhh', frame1)
        out.write(frame1)       
     
    elif lo >= 11000 and lo < 13000:
        
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        face_rects, scores, idx = detector.run(frame1, 0)  # 偵測人臉

        for i, d in enumerate(face_rects):                  # 取出所有偵測的結果
            x1 = d.left(); y1 = d.top(); x2 = d.right(); y2 = d.bottom()
            text = f'{scores[i]:.2f}, ({idx[i]:0.0f})'

            cv2.rectangle(frame1, (x1, y1), (x2, y2), (0, 255, 0), 4, cv2.LINE_AA) # 以方框標示偵測的人臉
            cv2.putText(frame1, text, (x1, y1), cv2.FONT_HERSHEY_DUPLEX,    # 標示分數
                0.7, (255, 255, 255), 1, cv2.LINE_AA)
        video.append(frame1)
        cv2.imshow('hhh', frame1)
        out.write(frame1)
    else:    
        break   
            
    k = cv2.waitKey(80) & 0xff
    if k == 27:
        break

# for i in video:
# #     cv2.imshow('original', i)
#     out.write(i)


cap.release()
out.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [ ]:
frame1

In [16]:
# import dlib
import cv2
import numpy as np

cap = cv2.VideoCapture('./hw_2.mp4')    # 開啟影片檔案

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))        # 取得畫面尺寸
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
fourcc = cv2.VideoWriter_fourcc(*'MJPG')             # 使用 XVID 編碼
video = []
# cap.set(cv2.CAP_PROP_POS_MSEC, 10000)               #  從第 10 秒開始撥放
# cap.set(cv2.CAP_PROP_POS_MSEC, 5000)
# 建立 VideoWriter 物件，輸出影片至 output.avi，FPS 值為 20.0
out = cv2.VideoWriter('./video/squid_game_03_finish.avi', fourcc, fps, (800, 450))
# detector = dlib.get_frontal_face_detector()          # Dlib 的人臉偵測器

while(cap.isOpened() and (cap.get(cv2.CAP_PROP_POS_MSEC) < 10000)):    # 以迴圈從影片檔案讀取影格，並顯示出來
    ret, frame = cap.read()
    print(frame)
    if ret:
        frame1 = cv2.resize(frame, (800, 450), interpolation = cv2.INTER_NEAREST)
        frame1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        cv2.putText(frame1, 'Gray', (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2, cv2.LINE_AA)
        cv2.imshow('hhh', frame1)
        out.write(frame1)
    else:
        break
  
    k = cv2.waitKey(80) & 0xff
    if k == 27:
        break

# for i in video:
# #     cv2.imshow('original', i)
#     out.write(i)


cap.release()
out.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[[115 108 105]
  [115 108 105]
  [115 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 [[115 108 105]
  [115 108 105]
  [115 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 [[115 108 105]
  [115 108 105]
  [115 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 ...

 [[ 47  61  75]
  [ 47  61  75]
  [ 43  59  73]
  ...
  [ 11  47  55]
  [ 16  43  52]
  [ 14  41  50]]

 [[ 45  59  73]
  [ 45  59  73]
  [ 43  59  73]
  ...
  [ 11  47  55]
  [ 16  43  52]
  [ 14  41  50]]

 [[ 45  59  73]
  [ 45  59  73]
  [ 43  59  73]
  ...
  [ 11  47  55]
  [ 16  43  52]
  [ 14  41  50]]]
[[[117 108 105]
  [117 108 105]
  [117 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 [[117 108 105]
  [117 108 105]
  [117 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 [[117 108 105]
  [117 108 105]
  [117 108 105]
  ...
  [117 109 104]
  [117 109 104]
  [117 109 104]]

 ...

 [[ 50  62  74]
  [ 50  62  74]
  [ 47  62  73]
  ..

-1